export interface restaurants{
  "_id": Object,           // Automatically generated by MongoDB
  "name": String,            // Name of the restaurant (e.g., "Spicy Kitchen")
  "rating": Number,          // Rating of the restaurant (e.g., 4.3)
  "address": String,
  "imgUrl":String,         // Address of the restaurant (e.g., "New Delhi, India")
  "dishes": [                // Array of dish objects
    {
      "name": String,  
      "imgUrl":String      // Name of the dish (e.g., "Paneer Butter Masala")
      "prices": [            // Array of quantity-price objects
        {
          "quantity": String, // e.g., "half" or "full"
          "price": Number     // Price corresponding to the quantity
        }
      ]
    }
  ]
}

export interface Dishes
            {
                name: String,
                imgUrl: String,
                prices: [
                    {
                        quantity: String,
                        price: Number
                    },
                    {
                        quantity: String,
                        price: Number
                    }
                ]
            }